### PR TITLE
openstack-db: remove out-of-date utility

### PR DESCRIPTION
**Pull request by hguemar**
Fixes: #19 

Next step will be preparing release.

### CODE REVIEW

**Comment by apevec** [comment]
:+1:

**Comment by yazug** [comment]
:+1:

**Comment by fuzzball81** [comment]
:thumbsup:

**Comment by hguemar** [comment]
Since there's 3 :+1: let's push the merge button :-)

**Comment by fuzzball81** [comment]
Need to update the README file to remove it as well.

**Pull request merged**
